// let kaam:unknown = 2025;
// kaam = "";
// let kaam_karo = kaam as string;
// kaam_karo = "insallah 2026, 27 tak men dosron ko help kar raha honga or wo bhi boht achy se";
// console.log(kaam_karo);
// let school:any = 2025;
// school = "inshallah 2025 men apna center open karonga idhr badin men";
// school = true;
// console.log(school);
var ukProject = "inshallah wo din bhi ab boht jald aaiga jab men usa men honga Google company men";
ukProject = 2025;
var usaWork = ukProject;
usaWork = 2026;
console.log(usaWork);
var dubaiapp = "mujahid time table pe focus kar";
dubaiapp = "2025;
